### ISSUE TITLE
Docker container does not recognize a new plugin if its a node module

### ISSUE THREAD

**Issue by abhagupta** [sitespeedio/sitespeed.io-docker#10]
Hi @soulgalore .. 
If I have a plugin to transform the data from sitespeed.io 4 into a new form and I want to use it with option `--plugins.load <myNodeModule>` , it does not recognize that module unless I give the path to my module's `main.js`.  It does recognize if you have `--plugins.load graphite` . I have not looked into the code, but    I am guessing this is because `graphite` and other plugins are registered somewhere inside sitespeed.io's code. 

Q1. How can I make my module recognized by `plugins.load` and not just by giving the path of my main.js file?

Q2. If I am using a docker container instead of `sitespeed.io`, then it becomes a real problem, because now you have to upload the volume with `node_modules` manually to container, and traverse to the `main.js` file of my module (which is real ugly). And if my module has a dependency which if not installed by `npm` restrictions of not installing dependencies more than once, my module will crash inside the container..

Any suggestions around these issues?

**Comment by soulgalore** [comment]
Ping @tobli lets sync this for best practice!

**Comment by soulgalore** [comment]
hey @abhagupta can you rename your main.js to index.js and will work automagically?

> Q1. How can I make my module recognized by plugins.load and not just by giving the path of my main.js file?

Using modules installed globally seems to be broken, lets fix that. Right now you need to point out where you have the plugin like  <pre>--plugins.load ../example-plugin/</pre>

> Q2.

No I think it would work by only mapping your plugin as a volume. Like git clone your project on the server, make sure you run <code>npm install</code> in your plugin dir and the do something like this:

<pre>
docker run -v /Users/peter/git/moment-plugin/:/moment-plugin sitespeedio/sitespeed.io -b firefox --plugins.load /moment-plugin -n 1 https://www.sitespeed.io
</pre>

I did a quick test and it worked for me but please test that is works fine for you.

There's a couple of things we can do to make it easier for plugins, like passing the log in the context, so each plugin could use the same log system as sitespeed.io. I'll fix that this weekend. And some other "utilities". We have a release coming up with some cool things in Browsertime that we hopefully release this weekend and then we can pass along some plugin fixes.
