### ISSUE TITLE
Image with bash / sh entrypoint

### ISSUE THREAD

**Issue by adilfulara** [sitespeedio/sitespeed.io-docker#12]
Would it be possible to get a docker image with sh / bash as the entry point. This would be helpful in ci / cd scenario. Ex: gitlab ci. 

In gitlab ci, you can select a docker image to be used as the container to perform your build step. We like to use sitespeed as a step in our pipeline and analyze our pages during testing phase. Gitlab doesn't yet support specifying an entry point for a docker image. currently workaround is to use the official image as a base and add an entry point.

**Comment by sebastien-prudhomme** [comment]
You can now use an empty entrypoint in GitLab CI. I can confirm it works fine with sitespeed.io official image.

See: https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#available-settings-for-image

**Comment by soulgalore** [comment]
Cool thanks for getting back @sebastien-prudhomme .

@adilfulara sorry I missed this issue.
