### ISSUE TITLE
Siteapeed.io is not capturing any Metrics as expected 

### ISSUE THREAD

**Issue by bsandeepreddy** [sitespeedio/sitespeed.io-docker#14]
I have sitespeed.io hosted on one of my Cloud servers running Red Hat Enterprise Linux Server release 7.3. I got sitespeed image through Docker and I have setup proxy that would establish the connectivity to get any images from the Docker Hub which confirms any network related impediments that would impact the usage. Now the issue is I have specified commands that I use to analyse any site but for some it would not Load the URL to get any metrics. Also looks like the containers get exited immediately I start it so that I can be assured that it is up and running(I may be wrong please correct me if I am - as I would be interested in learning more about this tool). Here are few screenshots representing my work. Also I am able to generate the results folder in which the metrics are blank. Please checkout the screenshot at the bottom confirming that.  
![sitespeed ioissuescreenshot](https://user-images.githubusercontent.com/13243847/30496155-90d9dc64-9a1c-11e7-910c-623f216908f0.JPG)

![sitespeed ioissuescreenshot_2](https://user-images.githubusercontent.com/13243847/30496220-b7cdc45c-9a1c-11e7-8883-1054b7b8a3c6.JPG)
![sitespeed ioissuescreenshot_containerstatus_images](https://user-images.githubusercontent.com/13243847/30496294-f0ad8046-9a1c-11e7-8064-4a9c393497f0.JPG)
![sitespeed ioissuescreenshot_detailedresultsummary](https://user-images.githubusercontent.com/13243847/30496516-a3910ca0-9a1d-11e7-9096-35f9b93dcd3b.JPG)

**Comment by soulgalore** [comment]
Hi @bsandeepreddy 
thanks for the report. I think we had reports on problems on Red Hat before and that time it was with Chrome and that you need to run it no-sandbox but we adds that automatically now. 

I would do like this:
1. Test adding --privileged when you run `docker run --shm-size=1g --privileged --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io --video --speedIndex https://YOURURL`
2. If that doesn't work, I would try with Firefox to see if it is Chrome related. Add **-b firefox** to your parameters to use Firefox.

Let me know what's the result!

Best
Peter
