### ISSUE TITLE
Error doing docker pull

### ISSUE THREAD

**Issue by geraldyeo** [sitespeedio/sitespeed.io-docker#2]
I'm following this [example](http://www.sitespeed.io/documentation/performance-dashboard/#example-setup-digital-ocean) to setup a droplet.

However I hit a snag with `sudo docker pull sitespeedio/sitespeeed.io`, which gives me this error `FATA[0004] Error: image sitespeedio/sitespeeed.io:latest not found`. 

Any idea how to proceed?

**Comment by soulgalore** [comment]
Hi @geraldyeo 
there's one e too many, try <code>sudo docker pull sitespeedio/sitespeed.io</code>

Best
Peter

**Comment by geraldyeo** [comment]
Hi @soulgalore 

Ah, missed that one. Thanks!

Probably need to update the typo on the website?

**Comment by soulgalore** [comment]
yes cool, let me fix that, thanks.

**Comment by soulgalore** [comment]
sorry again, my fault. the docs are updated now.

**Comment by geraldyeo** [comment]
Thanks and no worries, @soulgalore.

One more issue though, I'm getting error when I try to run Sitespeed.

`-bash: /tmp/sitespeed-run.txt: Permission denied`

I tried this when I did not get any output from crontab, and I could not access it from my DO server at the IP. I am logged in as `sitespeed` user when running through the tutorial.

_troubleshoot_

```
sudo docker run --privileged --rm -v /sitespeed.io:/sitespeed.io sitespeedio/sitespeed.io sitespeed.io -f urls.txt -b firefox -n 11 --connection cable -r /tmp/ --graphiteHost 128.199.244.189 --seleniumServer http://127.0.0.1:4444/wd/hub >> /tmp/sitespeed-run.txt 2>&1
```

_crontab (sudo crontab -e)_ 

```
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
0,15,30,45 * * * * docker run --privileged --rm -v /sitespeed.io:/sitespeed.io sitespeedio/sitespeed.io sitespeed.io -f urls.txt -b firefox -n 11 --connection cable -r /tmp/ --graphiteHost 128.199.244.189 --seleniumServer http://127.0.0.1:4444/wd/hub >> /tmp/sitespeed-run.txt 2>&1
```

**Comment by soulgalore** [comment]
Hi @geraldyeo ,
so could it be that root owns the  /tmp/sitespeed-run.txt file and you try to run as the sitespeedio user? just remove the /tmp/sitespeed-run.txt file and run again.

Best
Peter

**Comment by geraldyeo** [comment]
Hi @soulgalore,

Sorry, I'm very grateful for your help, but I'm a bit lost here. 

So these are my containers. What steps am I missing, so that I can access at my digital ocean IP, 128.199.244.189?

_edit:_ `sitespeed-run.txt` is populated with log entries, so I assume the containers are running.

`sudo docker ps`

```
CONTAINER ID        IMAGE                         COMMAND                CREATED             STATUS              PORTS                                          NAMES
de2ba0f1099c        grafana/grafana:latest        "/usr/sbin/grafana-s   7 minutes ago       Up 7 minutes        0.0.0.0:3000->3000/tcp                         grafana
e17d3564cf16        sitespeedio/graphite:latest   "/sbin/my_init"        About an hour ago   Up About an hour    0.0.0.0:2003->2003/tcp, 0.0.0.0:8080->80/tcp   graphite
```
