### ISSUE TITLE
Metrics for all page resources are being also sent together with the url metrics

### ISSUE THREAD

**Issue by xo4n** [sitespeedio/sitespeed.io-docker#4]
When running the sitespeed.io docker container from jenkins it sends metrics also for all the resources  (css, images, js, thirdparties) associated to the page. That generates thousands of metrics for each url being measured. Is it possible to send only the url related metrics? I have tried with the options

`
--graphiteData rules
`
and 
`
--graphiteData summary
`

but in all cases it also sends the "domains" metrics for each of the resources that have the following format

`
sitespeed.io.summary.www.trivago.com.domains.size.*
sitespeed.io.summary.www.trivago.com.domains.timings.*
`

As result we end up with more than 2000 metrics for just 1 url

The settings of the job are

`
15:04:38 + docker run --privileged --rm -v /appdata/jenkins/jobs/sitespeed.io.v3/workspace:/sitespeed.io sitespeedio/sitespeed.io sitespeed.io -v -u http://www.trivago.com -d 0 -b chrome,firefox -k true --screenshot --profile desktop --graphiteHost foo --graphitePort 2030 --graphiteData rules --resultBaseDir /sitespeed.io/../builds/68200 --outputFolderName report --suppressDomainFolder
15:04:38 Wed Sep 23 13:04:38 UTC 2015
15:04:38 ChromeDriver 2.14.313457 (3d645c400edf2e2c500566c9aa096063e707c9cf)
15:04:38 Google Chrome 44.0.2403.125 
15:04:38 Mozilla Firefox 40.0
15:04:38 Starting Xvfb ...
15:04:38 Starting Selenium server ... access it at http://127.0.0.1:4444/wd/hub
15:04:39 info: OS: 'linux 3.13.0-43-generic', Node.js: 'v0.10.25', sitespeed.io: '3.9.1', PhantomJS: '1.9.8', java: '1.7.0_79', browsertime: '0.11.0'
15:04:43 info: Will analyze 1 page
`

**Comment by soulgalore** [comment]
Hey @xo4n ,
thanks for adding the issue. It must be a bug, I'll try tonight or early tomorrow to recreate it (couldn't yesterday or it actuallt worked but I will try now when I have all your setup). 

This is what you can configure to send (if it works): https://www.sitespeed.io/documentation/performance-dashboard/#configure-sitespeedio-what-metrics-to-send

Will update the issue asap when I've tested.

Best
Peter

**Comment by soulgalore** [comment]
ah ok, yep tested. so if you run it with summary, it will actually only create the summary metrics, but in this case it will be almost 2000 metrics and the domains and timings are included in the summary, so you will get a lot of metrics. This isn't super clean but lets think if we can build the structure in another way. You should actually need to conigure what data you want in the summary right?

Running for multiple pages will not create the same amount for every URL, it will be 2000 in total but it will add new metrics if other pages uses other domains.

Best
Peter

**Comment by xo4n** [comment]
Actually I like the summary as it is, no need for me to reconfigure it, but why the Domain data that is in another section in the the generated html report should be sent together with the summary metrics? Is it not possible just to send the summary metrics when using the --summary option.

**Comment by soulgalore** [comment]
yeah but the domain (and domain timings) are summaries for all tested pages. Lets see, we could add one extra config just to skip them, I can do it this weekend and do release, will create an issue in sitespeed.io later today.

**Comment by soulgalore** [comment]
Hey @xo4n released 3.10.0, it will be in the Docker container in a couple of hours (our Chrome container has stopped on the Docker hub, when it's running again we wil push it with the latest version.

Ok, now if you specify only summary, the domains (and domain requests) will not be pushed.
