### ISSUE TITLE
Using alpine as base image

### ISSUE THREAD

**Issue by dev-rke** [sitespeedio/sitespeed.io-docker#7]
Hi,

might it be possible to base the docker images on the [alpine image](https://hub.docker.com/_/alpine/) in the future?
This would result in much smaller images.

**Comment by tobli** [comment]
Hi @dev-rke!
We'd love to see smaller images. However, looking at the latest 4.0 beta 2 image, the OS (Ubuntu 14) is only 188MB out of a 1.4GB image. So the savings wouldn't be that big. Most of the space is taken up by browsers and all other dependencies (node, xvfb, ffmpeg, python etc.).
The official images include dependencies needed for all features of Sitespeed.io. If you only need a subset of features (e.g. don't need videos, SpeedIndex metrics just one browser) you can absolutely loose a lot of MBs. Of course, if you have ideas for how to make the official images smaller, PRs are always welcome!

Thanks!
/Tobias
